export { default as polkadot } from './polkadot.svg'
export { default as kusama } from './kusama.svg'
export { default as globe } from './globe.svg'
export { default as astar } from './astar.svg'
export { default as bittensor } from './bittensor.svg'