// Copyright 2023-2024 @polkagate/snap authors & contributors
// SPDX-License-Identifier: Apache-2.0

export { default as exportAccount } from './exportAccount.svg'
export { default as ellipsisV } from './ellipsisV.svg'
export { default as metadata } from './metadata.svg'
export { default as send } from './send.svg'
export { default as settings } from './settings.svg'
export { default as stake } from './stake.svg'
export { default as vote } from './vote.svg'
export { default as more } from './more.svg'
export { default as twitter } from './twitter.svg'
export { default as book } from './book.svg'
export { default as webSite } from './webSite.svg'
export { default as email } from './email.svg'
export { default as youtube } from './youtube.svg'
export { default as success } from './success.svg'
export { default as hourglass } from './hourglass.svg'
export { default as coinStack } from './coinStack.svg'
export { default as timer } from './timer.svg'
export { default as reward } from './reward.svg'
export { default as alertBell } from './alertBell.svg'
export { default as solo } from './solo.svg'
export { default as pool } from './pool.svg'
export { default as polkagatePool } from './polkagatePool.svg'
export { default as fox } from './fox.svg'
export { default as poolSmall } from './poolSmall.svg'
export { default as soloSmall } from './soloSmall.svg'
export { default as activeIcon } from './activeIcon.svg'
export { default as birdUp } from './birdUp.svg'
export { default as birdDown } from './birdDown.svg'
export { default as clock } from './clock.svg'
export { default as working } from './working.svg'
export { default as ringingBell } from './ringingBell.svg'
export { default as info } from './info.svg'
export { default as account } from './account.svg'
export { default as inActiveIcon } from './inActiveIcon.svg'